"""initial schema: patients, samples, experiments, analyses, result_files

Revision ID: d42e5c3661a4
Revises: 
Create Date: 2026-09-04 12:43:08.924741

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd42e5c3661a4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('sample_type', sa.Enum('tumor', 'normal', name='sample_type_enum'), nullable=False),
    sa.Column('tissue', sa.String(length=64), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('sample_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_patient_id'), 'samples', ['patient_id'], unique=False)
    op.create_index(op.f('ix_samples_sample_id'), 'samples', ['sample_id'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('assay', sa.Enum('WGS', 'WES', 'RNA-seq', 'ATAC-seq', name='assay_type_enum'), nullable=False),
    sa.Column('sequencing_platform', sa.String(length=64), nullable=False),
    sa.Column('genome_build', sa.String(length=16), nullable=False),
    sa.Column('fastq_path', sa.String(length=512), nullable=True),
    sa.Column('bam_path', sa.String(length=512), nullable=True),
    sa.Column('experiment_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_assay'), 'experiments', ['assay'], unique=False)
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=True)
    op.create_index(op.f('ix_experiments_sample_id'), 'experiments', ['sample_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=128), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('reference_genome', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='analysis_status_enum'), server_default='queued', nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_experiment_id'), 'analyses', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('result_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('FASTQ', 'BAM', 'CRAM', 'VCF', 'TSV', 'OTHER', name='file_type_enum'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_files_analysis_id'), 'result_files', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_result_files_file_type'), 'result_files', ['file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_files_file_type'), table_name='result_files')
    op.drop_index(op.f('ix_result_files_analysis_id'), table_name='result_files')
    op.drop_table('result_files')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_experiment_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_experiments_sample_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_assay'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_samples_sample_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_patient_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
